# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02496165814278bf4e17ed7af9bf837181a16e9a9ac2a4c91316d3bcc3eb43ec7fb265fa591f8eba33a4ac621a9cefb46d880da0ab917cafbc26f64b01424e09

test:
  secret_key_base: 95823f75ead8f19ae71219103aba659da573430d1449f57b428b4e755626be51c44268307b55dc7108d95d866505a4e7a0afdcc93692579eadb8a9606102ab19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
